version : "3"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    volumes:
      # - "./mysql:/var/lib/mysql"
      # - "./initdb.d:/docker-entrypoint-initdb.d"
      - ./data:/var/lib/mysql:cached
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=leelee1!
      - MYSQL_DATABASE=leeuser
      - MYSQL_USER=leeuser
      - MYSQL_PASSWORD=leelee1!
      - MYSQL_ROOT_HOST=%

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=leelee1!
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
  
  jupyterkite:
    #https://www.idnet.co.jp/column/page_187.html
    build: 
      context: ./jupyter-kite
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    ports:
      - "8888:8888"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    # GPUを使う場合の設定
    # environment:
    #   - "NVIDIA_VISIBLE_DEVICES=all"
    #   - "NVIDIA_DRIVER_CAPABILITIES=all"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu

