version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./node_prj:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
